[package]
name = "core-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
config = "0.14.0"
dotenv = "0.15.0"
serde = { version = "1.0.204", features = ["derive"] }
tokio = { version = "1.38.1", features = ["full"] }
thiserror = "1.0.63"